import type { Metadata } from "next";
import "./globals.css";

// import { Inter } from 'next/font/google';

// Load the Inter font
// const inter = Inter({
//   subsets: ['latin'],
//   variable: '--font-inter',
// });

import { Poppins } from 'next/font/google';

// Load the Poppins font
const poppins = Poppins({
  subsets: ['latin'],
  weight: ['400', '500', '600'],
  variable: '--font-poppins',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.variable} font-sans antialiased bg-darkBlack`}
      >
        {children}
      </body>
    </html>
  );
}
